dist: bionic
language: cpp
compiler: gcc
script: make && make test
install:
    - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.11.4/protobuf-cpp-3.11.4.tar.gz
    - tar -xzvf protobuf-cpp-3.11.4.tar.gz
    - pushd protobuf-3.11.4 && ./configure --prefix=/usr && make && sudo make install && popd
