// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_message_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_message_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_message_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_message_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_message_2eproto;
class Message;
class MessageDefaultTypeInternal;
extern MessageDefaultTypeInternal _Message_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::Message* Arena::CreateMaybeMessage<::Message>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum Message_MsgType : int {
  Message_MsgType_PUBLISH_KEYS = 0,
  Message_MsgType_FETCH_KEYS_REQUEST = 1,
  Message_MsgType_FETCH_KEYS_RESPONSE = 2,
  Message_MsgType_INIT_MESSAGE = 3,
  Message_MsgType_MESSAGE = 4
};
bool Message_MsgType_IsValid(int value);
constexpr Message_MsgType Message_MsgType_MsgType_MIN = Message_MsgType_PUBLISH_KEYS;
constexpr Message_MsgType Message_MsgType_MsgType_MAX = Message_MsgType_MESSAGE;
constexpr int Message_MsgType_MsgType_ARRAYSIZE = Message_MsgType_MsgType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Message_MsgType_descriptor();
template<typename T>
inline const std::string& Message_MsgType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Message_MsgType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Message_MsgType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Message_MsgType_descriptor(), enum_t_value);
}
inline bool Message_MsgType_Parse(
    const std::string& name, Message_MsgType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Message_MsgType>(
    Message_MsgType_descriptor(), name, value);
}
// ===================================================================

class Message :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Message) */ {
 public:
  Message();
  virtual ~Message();

  Message(const Message& from);
  Message(Message&& from) noexcept
    : Message() {
    *this = ::std::move(from);
  }

  inline Message& operator=(const Message& from) {
    CopyFrom(from);
    return *this;
  }
  inline Message& operator=(Message&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Message& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Message* internal_default_instance() {
    return reinterpret_cast<const Message*>(
               &_Message_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Message& a, Message& b) {
    a.Swap(&b);
  }
  inline void Swap(Message* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Message* New() const final {
    return CreateMaybeMessage<Message>(nullptr);
  }

  Message* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Message>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Message& from);
  void MergeFrom(const Message& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Message* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Message";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_message_2eproto);
    return ::descriptor_table_message_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef Message_MsgType MsgType;
  static constexpr MsgType PUBLISH_KEYS =
    Message_MsgType_PUBLISH_KEYS;
  static constexpr MsgType FETCH_KEYS_REQUEST =
    Message_MsgType_FETCH_KEYS_REQUEST;
  static constexpr MsgType FETCH_KEYS_RESPONSE =
    Message_MsgType_FETCH_KEYS_RESPONSE;
  static constexpr MsgType INIT_MESSAGE =
    Message_MsgType_INIT_MESSAGE;
  static constexpr MsgType MESSAGE =
    Message_MsgType_MESSAGE;
  static inline bool MsgType_IsValid(int value) {
    return Message_MsgType_IsValid(value);
  }
  static constexpr MsgType MsgType_MIN =
    Message_MsgType_MsgType_MIN;
  static constexpr MsgType MsgType_MAX =
    Message_MsgType_MsgType_MAX;
  static constexpr int MsgType_ARRAYSIZE =
    Message_MsgType_MsgType_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  MsgType_descriptor() {
    return Message_MsgType_descriptor();
  }
  template<typename T>
  static inline const std::string& MsgType_Name(T enum_t_value) {
    static_assert(::std::is_same<T, MsgType>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function MsgType_Name.");
    return Message_MsgType_Name(enum_t_value);
  }
  static inline bool MsgType_Parse(const std::string& name,
      MsgType* value) {
    return Message_MsgType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kSenOTPFieldNumber = 6,
    kSenIdKeyFieldNumber = 3,
    kSenPreKeyFieldNumber = 4,
    kSenPreKeySigFieldNumber = 5,
    kReqIdKeyFieldNumber = 8,
    kReqPreKeyFieldNumber = 9,
    kReqPreKeySigFieldNumber = 10,
    kReqOTPFieldNumber = 11,
    kSenEpKeyFieldNumber = 12,
    kCTFieldNumber = 14,
    kSenRKeyFieldNumber = 17,
    kTextContentFieldNumber = 19,
    kTimestampFieldNumber = 20,
    kTypeFieldNumber = 1,
    kSenIdFieldNumber = 2,
    kReqIdFieldNumber = 7,
    kOTPidFieldNumber = 13,
    kMessNumFieldNumber = 15,
    kPrevNumFieldNumber = 16,
    kRecIdFieldNumber = 18,
  };
  // repeated bytes senOTP = 6;
  int senotp_size() const;
  private:
  int _internal_senotp_size() const;
  public:
  void clear_senotp();
  const std::string& senotp(int index) const;
  std::string* mutable_senotp(int index);
  void set_senotp(int index, const std::string& value);
  void set_senotp(int index, std::string&& value);
  void set_senotp(int index, const char* value);
  void set_senotp(int index, const void* value, size_t size);
  std::string* add_senotp();
  void add_senotp(const std::string& value);
  void add_senotp(std::string&& value);
  void add_senotp(const char* value);
  void add_senotp(const void* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& senotp() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_senotp();
  private:
  const std::string& _internal_senotp(int index) const;
  std::string* _internal_add_senotp();
  public:

  // optional bytes senIdKey = 3;
  bool has_senidkey() const;
  private:
  bool _internal_has_senidkey() const;
  public:
  void clear_senidkey();
  const std::string& senidkey() const;
  void set_senidkey(const std::string& value);
  void set_senidkey(std::string&& value);
  void set_senidkey(const char* value);
  void set_senidkey(const void* value, size_t size);
  std::string* mutable_senidkey();
  std::string* release_senidkey();
  void set_allocated_senidkey(std::string* senidkey);
  private:
  const std::string& _internal_senidkey() const;
  void _internal_set_senidkey(const std::string& value);
  std::string* _internal_mutable_senidkey();
  public:

  // optional bytes senPreKey = 4;
  bool has_senprekey() const;
  private:
  bool _internal_has_senprekey() const;
  public:
  void clear_senprekey();
  const std::string& senprekey() const;
  void set_senprekey(const std::string& value);
  void set_senprekey(std::string&& value);
  void set_senprekey(const char* value);
  void set_senprekey(const void* value, size_t size);
  std::string* mutable_senprekey();
  std::string* release_senprekey();
  void set_allocated_senprekey(std::string* senprekey);
  private:
  const std::string& _internal_senprekey() const;
  void _internal_set_senprekey(const std::string& value);
  std::string* _internal_mutable_senprekey();
  public:

  // optional bytes senPreKeySig = 5;
  bool has_senprekeysig() const;
  private:
  bool _internal_has_senprekeysig() const;
  public:
  void clear_senprekeysig();
  const std::string& senprekeysig() const;
  void set_senprekeysig(const std::string& value);
  void set_senprekeysig(std::string&& value);
  void set_senprekeysig(const char* value);
  void set_senprekeysig(const void* value, size_t size);
  std::string* mutable_senprekeysig();
  std::string* release_senprekeysig();
  void set_allocated_senprekeysig(std::string* senprekeysig);
  private:
  const std::string& _internal_senprekeysig() const;
  void _internal_set_senprekeysig(const std::string& value);
  std::string* _internal_mutable_senprekeysig();
  public:

  // optional bytes reqIdKey = 8;
  bool has_reqidkey() const;
  private:
  bool _internal_has_reqidkey() const;
  public:
  void clear_reqidkey();
  const std::string& reqidkey() const;
  void set_reqidkey(const std::string& value);
  void set_reqidkey(std::string&& value);
  void set_reqidkey(const char* value);
  void set_reqidkey(const void* value, size_t size);
  std::string* mutable_reqidkey();
  std::string* release_reqidkey();
  void set_allocated_reqidkey(std::string* reqidkey);
  private:
  const std::string& _internal_reqidkey() const;
  void _internal_set_reqidkey(const std::string& value);
  std::string* _internal_mutable_reqidkey();
  public:

  // optional bytes reqPreKey = 9;
  bool has_reqprekey() const;
  private:
  bool _internal_has_reqprekey() const;
  public:
  void clear_reqprekey();
  const std::string& reqprekey() const;
  void set_reqprekey(const std::string& value);
  void set_reqprekey(std::string&& value);
  void set_reqprekey(const char* value);
  void set_reqprekey(const void* value, size_t size);
  std::string* mutable_reqprekey();
  std::string* release_reqprekey();
  void set_allocated_reqprekey(std::string* reqprekey);
  private:
  const std::string& _internal_reqprekey() const;
  void _internal_set_reqprekey(const std::string& value);
  std::string* _internal_mutable_reqprekey();
  public:

  // optional bytes reqPreKeySig = 10;
  bool has_reqprekeysig() const;
  private:
  bool _internal_has_reqprekeysig() const;
  public:
  void clear_reqprekeysig();
  const std::string& reqprekeysig() const;
  void set_reqprekeysig(const std::string& value);
  void set_reqprekeysig(std::string&& value);
  void set_reqprekeysig(const char* value);
  void set_reqprekeysig(const void* value, size_t size);
  std::string* mutable_reqprekeysig();
  std::string* release_reqprekeysig();
  void set_allocated_reqprekeysig(std::string* reqprekeysig);
  private:
  const std::string& _internal_reqprekeysig() const;
  void _internal_set_reqprekeysig(const std::string& value);
  std::string* _internal_mutable_reqprekeysig();
  public:

  // optional bytes reqOTP = 11;
  bool has_reqotp() const;
  private:
  bool _internal_has_reqotp() const;
  public:
  void clear_reqotp();
  const std::string& reqotp() const;
  void set_reqotp(const std::string& value);
  void set_reqotp(std::string&& value);
  void set_reqotp(const char* value);
  void set_reqotp(const void* value, size_t size);
  std::string* mutable_reqotp();
  std::string* release_reqotp();
  void set_allocated_reqotp(std::string* reqotp);
  private:
  const std::string& _internal_reqotp() const;
  void _internal_set_reqotp(const std::string& value);
  std::string* _internal_mutable_reqotp();
  public:

  // optional bytes senEpKey = 12;
  bool has_senepkey() const;
  private:
  bool _internal_has_senepkey() const;
  public:
  void clear_senepkey();
  const std::string& senepkey() const;
  void set_senepkey(const std::string& value);
  void set_senepkey(std::string&& value);
  void set_senepkey(const char* value);
  void set_senepkey(const void* value, size_t size);
  std::string* mutable_senepkey();
  std::string* release_senepkey();
  void set_allocated_senepkey(std::string* senepkey);
  private:
  const std::string& _internal_senepkey() const;
  void _internal_set_senepkey(const std::string& value);
  std::string* _internal_mutable_senepkey();
  public:

  // optional bytes CT = 14;
  bool has_ct() const;
  private:
  bool _internal_has_ct() const;
  public:
  void clear_ct();
  const std::string& ct() const;
  void set_ct(const std::string& value);
  void set_ct(std::string&& value);
  void set_ct(const char* value);
  void set_ct(const void* value, size_t size);
  std::string* mutable_ct();
  std::string* release_ct();
  void set_allocated_ct(std::string* ct);
  private:
  const std::string& _internal_ct() const;
  void _internal_set_ct(const std::string& value);
  std::string* _internal_mutable_ct();
  public:

  // optional bytes senRKey = 17;
  bool has_senrkey() const;
  private:
  bool _internal_has_senrkey() const;
  public:
  void clear_senrkey();
  const std::string& senrkey() const;
  void set_senrkey(const std::string& value);
  void set_senrkey(std::string&& value);
  void set_senrkey(const char* value);
  void set_senrkey(const void* value, size_t size);
  std::string* mutable_senrkey();
  std::string* release_senrkey();
  void set_allocated_senrkey(std::string* senrkey);
  private:
  const std::string& _internal_senrkey() const;
  void _internal_set_senrkey(const std::string& value);
  std::string* _internal_mutable_senrkey();
  public:

  // optional string textContent = 19;
  bool has_textcontent() const;
  private:
  bool _internal_has_textcontent() const;
  public:
  void clear_textcontent();
  const std::string& textcontent() const;
  void set_textcontent(const std::string& value);
  void set_textcontent(std::string&& value);
  void set_textcontent(const char* value);
  void set_textcontent(const char* value, size_t size);
  std::string* mutable_textcontent();
  std::string* release_textcontent();
  void set_allocated_textcontent(std::string* textcontent);
  private:
  const std::string& _internal_textcontent() const;
  void _internal_set_textcontent(const std::string& value);
  std::string* _internal_mutable_textcontent();
  public:

  // optional string timestamp = 20;
  bool has_timestamp() const;
  private:
  bool _internal_has_timestamp() const;
  public:
  void clear_timestamp();
  const std::string& timestamp() const;
  void set_timestamp(const std::string& value);
  void set_timestamp(std::string&& value);
  void set_timestamp(const char* value);
  void set_timestamp(const char* value, size_t size);
  std::string* mutable_timestamp();
  std::string* release_timestamp();
  void set_allocated_timestamp(std::string* timestamp);
  private:
  const std::string& _internal_timestamp() const;
  void _internal_set_timestamp(const std::string& value);
  std::string* _internal_mutable_timestamp();
  public:

  // required .Message.MsgType type = 1;
  bool has_type() const;
  private:
  bool _internal_has_type() const;
  public:
  void clear_type();
  ::Message_MsgType type() const;
  void set_type(::Message_MsgType value);
  private:
  ::Message_MsgType _internal_type() const;
  void _internal_set_type(::Message_MsgType value);
  public:

  // optional int32 senId = 2;
  bool has_senid() const;
  private:
  bool _internal_has_senid() const;
  public:
  void clear_senid();
  ::PROTOBUF_NAMESPACE_ID::int32 senid() const;
  void set_senid(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_senid() const;
  void _internal_set_senid(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // optional int32 reqId = 7;
  bool has_reqid() const;
  private:
  bool _internal_has_reqid() const;
  public:
  void clear_reqid();
  ::PROTOBUF_NAMESPACE_ID::int32 reqid() const;
  void set_reqid(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_reqid() const;
  void _internal_set_reqid(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // optional int32 OTPid = 13;
  bool has_otpid() const;
  private:
  bool _internal_has_otpid() const;
  public:
  void clear_otpid();
  ::PROTOBUF_NAMESPACE_ID::int32 otpid() const;
  void set_otpid(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_otpid() const;
  void _internal_set_otpid(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // optional int32 messNum = 15;
  bool has_messnum() const;
  private:
  bool _internal_has_messnum() const;
  public:
  void clear_messnum();
  ::PROTOBUF_NAMESPACE_ID::int32 messnum() const;
  void set_messnum(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_messnum() const;
  void _internal_set_messnum(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // optional int32 prevNum = 16;
  bool has_prevnum() const;
  private:
  bool _internal_has_prevnum() const;
  public:
  void clear_prevnum();
  ::PROTOBUF_NAMESPACE_ID::int32 prevnum() const;
  void set_prevnum(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_prevnum() const;
  void _internal_set_prevnum(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // optional int32 recId = 18;
  bool has_recid() const;
  private:
  bool _internal_has_recid() const;
  public:
  void clear_recid();
  ::PROTOBUF_NAMESPACE_ID::int32 recid() const;
  void set_recid(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_recid() const;
  void _internal_set_recid(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:Message)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> senotp_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr senidkey_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr senprekey_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr senprekeysig_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr reqidkey_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr reqprekey_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr reqprekeysig_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr reqotp_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr senepkey_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ct_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr senrkey_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr textcontent_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr timestamp_;
  int type_;
  ::PROTOBUF_NAMESPACE_ID::int32 senid_;
  ::PROTOBUF_NAMESPACE_ID::int32 reqid_;
  ::PROTOBUF_NAMESPACE_ID::int32 otpid_;
  ::PROTOBUF_NAMESPACE_ID::int32 messnum_;
  ::PROTOBUF_NAMESPACE_ID::int32 prevnum_;
  ::PROTOBUF_NAMESPACE_ID::int32 recid_;
  friend struct ::TableStruct_message_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Message

// required .Message.MsgType type = 1;
inline bool Message::_internal_has_type() const {
  bool value = (_has_bits_[0] & 0x00001000u) != 0;
  return value;
}
inline bool Message::has_type() const {
  return _internal_has_type();
}
inline void Message::clear_type() {
  type_ = 0;
  _has_bits_[0] &= ~0x00001000u;
}
inline ::Message_MsgType Message::_internal_type() const {
  return static_cast< ::Message_MsgType >(type_);
}
inline ::Message_MsgType Message::type() const {
  // @@protoc_insertion_point(field_get:Message.type)
  return _internal_type();
}
inline void Message::_internal_set_type(::Message_MsgType value) {
  assert(::Message_MsgType_IsValid(value));
  _has_bits_[0] |= 0x00001000u;
  type_ = value;
}
inline void Message::set_type(::Message_MsgType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:Message.type)
}

// optional int32 senId = 2;
inline bool Message::_internal_has_senid() const {
  bool value = (_has_bits_[0] & 0x00002000u) != 0;
  return value;
}
inline bool Message::has_senid() const {
  return _internal_has_senid();
}
inline void Message::clear_senid() {
  senid_ = 0;
  _has_bits_[0] &= ~0x00002000u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Message::_internal_senid() const {
  return senid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Message::senid() const {
  // @@protoc_insertion_point(field_get:Message.senId)
  return _internal_senid();
}
inline void Message::_internal_set_senid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00002000u;
  senid_ = value;
}
inline void Message::set_senid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_senid(value);
  // @@protoc_insertion_point(field_set:Message.senId)
}

// optional bytes senIdKey = 3;
inline bool Message::_internal_has_senidkey() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Message::has_senidkey() const {
  return _internal_has_senidkey();
}
inline void Message::clear_senidkey() {
  senidkey_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Message::senidkey() const {
  // @@protoc_insertion_point(field_get:Message.senIdKey)
  return _internal_senidkey();
}
inline void Message::set_senidkey(const std::string& value) {
  _internal_set_senidkey(value);
  // @@protoc_insertion_point(field_set:Message.senIdKey)
}
inline std::string* Message::mutable_senidkey() {
  // @@protoc_insertion_point(field_mutable:Message.senIdKey)
  return _internal_mutable_senidkey();
}
inline const std::string& Message::_internal_senidkey() const {
  return senidkey_.GetNoArena();
}
inline void Message::_internal_set_senidkey(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  senidkey_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void Message::set_senidkey(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  senidkey_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Message.senIdKey)
}
inline void Message::set_senidkey(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  senidkey_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Message.senIdKey)
}
inline void Message::set_senidkey(const void* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  senidkey_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Message.senIdKey)
}
inline std::string* Message::_internal_mutable_senidkey() {
  _has_bits_[0] |= 0x00000001u;
  return senidkey_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Message::release_senidkey() {
  // @@protoc_insertion_point(field_release:Message.senIdKey)
  if (!_internal_has_senidkey()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return senidkey_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Message::set_allocated_senidkey(std::string* senidkey) {
  if (senidkey != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  senidkey_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), senidkey);
  // @@protoc_insertion_point(field_set_allocated:Message.senIdKey)
}

// optional bytes senPreKey = 4;
inline bool Message::_internal_has_senprekey() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Message::has_senprekey() const {
  return _internal_has_senprekey();
}
inline void Message::clear_senprekey() {
  senprekey_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& Message::senprekey() const {
  // @@protoc_insertion_point(field_get:Message.senPreKey)
  return _internal_senprekey();
}
inline void Message::set_senprekey(const std::string& value) {
  _internal_set_senprekey(value);
  // @@protoc_insertion_point(field_set:Message.senPreKey)
}
inline std::string* Message::mutable_senprekey() {
  // @@protoc_insertion_point(field_mutable:Message.senPreKey)
  return _internal_mutable_senprekey();
}
inline const std::string& Message::_internal_senprekey() const {
  return senprekey_.GetNoArena();
}
inline void Message::_internal_set_senprekey(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  senprekey_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void Message::set_senprekey(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  senprekey_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Message.senPreKey)
}
inline void Message::set_senprekey(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  senprekey_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Message.senPreKey)
}
inline void Message::set_senprekey(const void* value, size_t size) {
  _has_bits_[0] |= 0x00000002u;
  senprekey_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Message.senPreKey)
}
inline std::string* Message::_internal_mutable_senprekey() {
  _has_bits_[0] |= 0x00000002u;
  return senprekey_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Message::release_senprekey() {
  // @@protoc_insertion_point(field_release:Message.senPreKey)
  if (!_internal_has_senprekey()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return senprekey_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Message::set_allocated_senprekey(std::string* senprekey) {
  if (senprekey != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  senprekey_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), senprekey);
  // @@protoc_insertion_point(field_set_allocated:Message.senPreKey)
}

// optional bytes senPreKeySig = 5;
inline bool Message::_internal_has_senprekeysig() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Message::has_senprekeysig() const {
  return _internal_has_senprekeysig();
}
inline void Message::clear_senprekeysig() {
  senprekeysig_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000004u;
}
inline const std::string& Message::senprekeysig() const {
  // @@protoc_insertion_point(field_get:Message.senPreKeySig)
  return _internal_senprekeysig();
}
inline void Message::set_senprekeysig(const std::string& value) {
  _internal_set_senprekeysig(value);
  // @@protoc_insertion_point(field_set:Message.senPreKeySig)
}
inline std::string* Message::mutable_senprekeysig() {
  // @@protoc_insertion_point(field_mutable:Message.senPreKeySig)
  return _internal_mutable_senprekeysig();
}
inline const std::string& Message::_internal_senprekeysig() const {
  return senprekeysig_.GetNoArena();
}
inline void Message::_internal_set_senprekeysig(const std::string& value) {
  _has_bits_[0] |= 0x00000004u;
  senprekeysig_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void Message::set_senprekeysig(std::string&& value) {
  _has_bits_[0] |= 0x00000004u;
  senprekeysig_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Message.senPreKeySig)
}
inline void Message::set_senprekeysig(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000004u;
  senprekeysig_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Message.senPreKeySig)
}
inline void Message::set_senprekeysig(const void* value, size_t size) {
  _has_bits_[0] |= 0x00000004u;
  senprekeysig_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Message.senPreKeySig)
}
inline std::string* Message::_internal_mutable_senprekeysig() {
  _has_bits_[0] |= 0x00000004u;
  return senprekeysig_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Message::release_senprekeysig() {
  // @@protoc_insertion_point(field_release:Message.senPreKeySig)
  if (!_internal_has_senprekeysig()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000004u;
  return senprekeysig_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Message::set_allocated_senprekeysig(std::string* senprekeysig) {
  if (senprekeysig != nullptr) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  senprekeysig_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), senprekeysig);
  // @@protoc_insertion_point(field_set_allocated:Message.senPreKeySig)
}

// repeated bytes senOTP = 6;
inline int Message::_internal_senotp_size() const {
  return senotp_.size();
}
inline int Message::senotp_size() const {
  return _internal_senotp_size();
}
inline void Message::clear_senotp() {
  senotp_.Clear();
}
inline std::string* Message::add_senotp() {
  // @@protoc_insertion_point(field_add_mutable:Message.senOTP)
  return _internal_add_senotp();
}
inline const std::string& Message::_internal_senotp(int index) const {
  return senotp_.Get(index);
}
inline const std::string& Message::senotp(int index) const {
  // @@protoc_insertion_point(field_get:Message.senOTP)
  return _internal_senotp(index);
}
inline std::string* Message::mutable_senotp(int index) {
  // @@protoc_insertion_point(field_mutable:Message.senOTP)
  return senotp_.Mutable(index);
}
inline void Message::set_senotp(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:Message.senOTP)
  senotp_.Mutable(index)->assign(value);
}
inline void Message::set_senotp(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:Message.senOTP)
  senotp_.Mutable(index)->assign(std::move(value));
}
inline void Message::set_senotp(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  senotp_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:Message.senOTP)
}
inline void Message::set_senotp(int index, const void* value, size_t size) {
  senotp_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Message.senOTP)
}
inline std::string* Message::_internal_add_senotp() {
  return senotp_.Add();
}
inline void Message::add_senotp(const std::string& value) {
  senotp_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:Message.senOTP)
}
inline void Message::add_senotp(std::string&& value) {
  senotp_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:Message.senOTP)
}
inline void Message::add_senotp(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  senotp_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:Message.senOTP)
}
inline void Message::add_senotp(const void* value, size_t size) {
  senotp_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:Message.senOTP)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
Message::senotp() const {
  // @@protoc_insertion_point(field_list:Message.senOTP)
  return senotp_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
Message::mutable_senotp() {
  // @@protoc_insertion_point(field_mutable_list:Message.senOTP)
  return &senotp_;
}

// optional int32 reqId = 7;
inline bool Message::_internal_has_reqid() const {
  bool value = (_has_bits_[0] & 0x00004000u) != 0;
  return value;
}
inline bool Message::has_reqid() const {
  return _internal_has_reqid();
}
inline void Message::clear_reqid() {
  reqid_ = 0;
  _has_bits_[0] &= ~0x00004000u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Message::_internal_reqid() const {
  return reqid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Message::reqid() const {
  // @@protoc_insertion_point(field_get:Message.reqId)
  return _internal_reqid();
}
inline void Message::_internal_set_reqid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00004000u;
  reqid_ = value;
}
inline void Message::set_reqid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_reqid(value);
  // @@protoc_insertion_point(field_set:Message.reqId)
}

// optional bytes reqIdKey = 8;
inline bool Message::_internal_has_reqidkey() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool Message::has_reqidkey() const {
  return _internal_has_reqidkey();
}
inline void Message::clear_reqidkey() {
  reqidkey_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000008u;
}
inline const std::string& Message::reqidkey() const {
  // @@protoc_insertion_point(field_get:Message.reqIdKey)
  return _internal_reqidkey();
}
inline void Message::set_reqidkey(const std::string& value) {
  _internal_set_reqidkey(value);
  // @@protoc_insertion_point(field_set:Message.reqIdKey)
}
inline std::string* Message::mutable_reqidkey() {
  // @@protoc_insertion_point(field_mutable:Message.reqIdKey)
  return _internal_mutable_reqidkey();
}
inline const std::string& Message::_internal_reqidkey() const {
  return reqidkey_.GetNoArena();
}
inline void Message::_internal_set_reqidkey(const std::string& value) {
  _has_bits_[0] |= 0x00000008u;
  reqidkey_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void Message::set_reqidkey(std::string&& value) {
  _has_bits_[0] |= 0x00000008u;
  reqidkey_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Message.reqIdKey)
}
inline void Message::set_reqidkey(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000008u;
  reqidkey_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Message.reqIdKey)
}
inline void Message::set_reqidkey(const void* value, size_t size) {
  _has_bits_[0] |= 0x00000008u;
  reqidkey_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Message.reqIdKey)
}
inline std::string* Message::_internal_mutable_reqidkey() {
  _has_bits_[0] |= 0x00000008u;
  return reqidkey_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Message::release_reqidkey() {
  // @@protoc_insertion_point(field_release:Message.reqIdKey)
  if (!_internal_has_reqidkey()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000008u;
  return reqidkey_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Message::set_allocated_reqidkey(std::string* reqidkey) {
  if (reqidkey != nullptr) {
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  reqidkey_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), reqidkey);
  // @@protoc_insertion_point(field_set_allocated:Message.reqIdKey)
}

// optional bytes reqPreKey = 9;
inline bool Message::_internal_has_reqprekey() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool Message::has_reqprekey() const {
  return _internal_has_reqprekey();
}
inline void Message::clear_reqprekey() {
  reqprekey_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000010u;
}
inline const std::string& Message::reqprekey() const {
  // @@protoc_insertion_point(field_get:Message.reqPreKey)
  return _internal_reqprekey();
}
inline void Message::set_reqprekey(const std::string& value) {
  _internal_set_reqprekey(value);
  // @@protoc_insertion_point(field_set:Message.reqPreKey)
}
inline std::string* Message::mutable_reqprekey() {
  // @@protoc_insertion_point(field_mutable:Message.reqPreKey)
  return _internal_mutable_reqprekey();
}
inline const std::string& Message::_internal_reqprekey() const {
  return reqprekey_.GetNoArena();
}
inline void Message::_internal_set_reqprekey(const std::string& value) {
  _has_bits_[0] |= 0x00000010u;
  reqprekey_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void Message::set_reqprekey(std::string&& value) {
  _has_bits_[0] |= 0x00000010u;
  reqprekey_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Message.reqPreKey)
}
inline void Message::set_reqprekey(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000010u;
  reqprekey_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Message.reqPreKey)
}
inline void Message::set_reqprekey(const void* value, size_t size) {
  _has_bits_[0] |= 0x00000010u;
  reqprekey_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Message.reqPreKey)
}
inline std::string* Message::_internal_mutable_reqprekey() {
  _has_bits_[0] |= 0x00000010u;
  return reqprekey_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Message::release_reqprekey() {
  // @@protoc_insertion_point(field_release:Message.reqPreKey)
  if (!_internal_has_reqprekey()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000010u;
  return reqprekey_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Message::set_allocated_reqprekey(std::string* reqprekey) {
  if (reqprekey != nullptr) {
    _has_bits_[0] |= 0x00000010u;
  } else {
    _has_bits_[0] &= ~0x00000010u;
  }
  reqprekey_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), reqprekey);
  // @@protoc_insertion_point(field_set_allocated:Message.reqPreKey)
}

// optional bytes reqPreKeySig = 10;
inline bool Message::_internal_has_reqprekeysig() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool Message::has_reqprekeysig() const {
  return _internal_has_reqprekeysig();
}
inline void Message::clear_reqprekeysig() {
  reqprekeysig_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000020u;
}
inline const std::string& Message::reqprekeysig() const {
  // @@protoc_insertion_point(field_get:Message.reqPreKeySig)
  return _internal_reqprekeysig();
}
inline void Message::set_reqprekeysig(const std::string& value) {
  _internal_set_reqprekeysig(value);
  // @@protoc_insertion_point(field_set:Message.reqPreKeySig)
}
inline std::string* Message::mutable_reqprekeysig() {
  // @@protoc_insertion_point(field_mutable:Message.reqPreKeySig)
  return _internal_mutable_reqprekeysig();
}
inline const std::string& Message::_internal_reqprekeysig() const {
  return reqprekeysig_.GetNoArena();
}
inline void Message::_internal_set_reqprekeysig(const std::string& value) {
  _has_bits_[0] |= 0x00000020u;
  reqprekeysig_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void Message::set_reqprekeysig(std::string&& value) {
  _has_bits_[0] |= 0x00000020u;
  reqprekeysig_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Message.reqPreKeySig)
}
inline void Message::set_reqprekeysig(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000020u;
  reqprekeysig_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Message.reqPreKeySig)
}
inline void Message::set_reqprekeysig(const void* value, size_t size) {
  _has_bits_[0] |= 0x00000020u;
  reqprekeysig_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Message.reqPreKeySig)
}
inline std::string* Message::_internal_mutable_reqprekeysig() {
  _has_bits_[0] |= 0x00000020u;
  return reqprekeysig_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Message::release_reqprekeysig() {
  // @@protoc_insertion_point(field_release:Message.reqPreKeySig)
  if (!_internal_has_reqprekeysig()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000020u;
  return reqprekeysig_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Message::set_allocated_reqprekeysig(std::string* reqprekeysig) {
  if (reqprekeysig != nullptr) {
    _has_bits_[0] |= 0x00000020u;
  } else {
    _has_bits_[0] &= ~0x00000020u;
  }
  reqprekeysig_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), reqprekeysig);
  // @@protoc_insertion_point(field_set_allocated:Message.reqPreKeySig)
}

// optional bytes reqOTP = 11;
inline bool Message::_internal_has_reqotp() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool Message::has_reqotp() const {
  return _internal_has_reqotp();
}
inline void Message::clear_reqotp() {
  reqotp_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000040u;
}
inline const std::string& Message::reqotp() const {
  // @@protoc_insertion_point(field_get:Message.reqOTP)
  return _internal_reqotp();
}
inline void Message::set_reqotp(const std::string& value) {
  _internal_set_reqotp(value);
  // @@protoc_insertion_point(field_set:Message.reqOTP)
}
inline std::string* Message::mutable_reqotp() {
  // @@protoc_insertion_point(field_mutable:Message.reqOTP)
  return _internal_mutable_reqotp();
}
inline const std::string& Message::_internal_reqotp() const {
  return reqotp_.GetNoArena();
}
inline void Message::_internal_set_reqotp(const std::string& value) {
  _has_bits_[0] |= 0x00000040u;
  reqotp_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void Message::set_reqotp(std::string&& value) {
  _has_bits_[0] |= 0x00000040u;
  reqotp_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Message.reqOTP)
}
inline void Message::set_reqotp(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000040u;
  reqotp_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Message.reqOTP)
}
inline void Message::set_reqotp(const void* value, size_t size) {
  _has_bits_[0] |= 0x00000040u;
  reqotp_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Message.reqOTP)
}
inline std::string* Message::_internal_mutable_reqotp() {
  _has_bits_[0] |= 0x00000040u;
  return reqotp_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Message::release_reqotp() {
  // @@protoc_insertion_point(field_release:Message.reqOTP)
  if (!_internal_has_reqotp()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000040u;
  return reqotp_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Message::set_allocated_reqotp(std::string* reqotp) {
  if (reqotp != nullptr) {
    _has_bits_[0] |= 0x00000040u;
  } else {
    _has_bits_[0] &= ~0x00000040u;
  }
  reqotp_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), reqotp);
  // @@protoc_insertion_point(field_set_allocated:Message.reqOTP)
}

// optional bytes senEpKey = 12;
inline bool Message::_internal_has_senepkey() const {
  bool value = (_has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool Message::has_senepkey() const {
  return _internal_has_senepkey();
}
inline void Message::clear_senepkey() {
  senepkey_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000080u;
}
inline const std::string& Message::senepkey() const {
  // @@protoc_insertion_point(field_get:Message.senEpKey)
  return _internal_senepkey();
}
inline void Message::set_senepkey(const std::string& value) {
  _internal_set_senepkey(value);
  // @@protoc_insertion_point(field_set:Message.senEpKey)
}
inline std::string* Message::mutable_senepkey() {
  // @@protoc_insertion_point(field_mutable:Message.senEpKey)
  return _internal_mutable_senepkey();
}
inline const std::string& Message::_internal_senepkey() const {
  return senepkey_.GetNoArena();
}
inline void Message::_internal_set_senepkey(const std::string& value) {
  _has_bits_[0] |= 0x00000080u;
  senepkey_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void Message::set_senepkey(std::string&& value) {
  _has_bits_[0] |= 0x00000080u;
  senepkey_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Message.senEpKey)
}
inline void Message::set_senepkey(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000080u;
  senepkey_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Message.senEpKey)
}
inline void Message::set_senepkey(const void* value, size_t size) {
  _has_bits_[0] |= 0x00000080u;
  senepkey_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Message.senEpKey)
}
inline std::string* Message::_internal_mutable_senepkey() {
  _has_bits_[0] |= 0x00000080u;
  return senepkey_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Message::release_senepkey() {
  // @@protoc_insertion_point(field_release:Message.senEpKey)
  if (!_internal_has_senepkey()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000080u;
  return senepkey_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Message::set_allocated_senepkey(std::string* senepkey) {
  if (senepkey != nullptr) {
    _has_bits_[0] |= 0x00000080u;
  } else {
    _has_bits_[0] &= ~0x00000080u;
  }
  senepkey_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), senepkey);
  // @@protoc_insertion_point(field_set_allocated:Message.senEpKey)
}

// optional int32 OTPid = 13;
inline bool Message::_internal_has_otpid() const {
  bool value = (_has_bits_[0] & 0x00008000u) != 0;
  return value;
}
inline bool Message::has_otpid() const {
  return _internal_has_otpid();
}
inline void Message::clear_otpid() {
  otpid_ = 0;
  _has_bits_[0] &= ~0x00008000u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Message::_internal_otpid() const {
  return otpid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Message::otpid() const {
  // @@protoc_insertion_point(field_get:Message.OTPid)
  return _internal_otpid();
}
inline void Message::_internal_set_otpid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00008000u;
  otpid_ = value;
}
inline void Message::set_otpid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_otpid(value);
  // @@protoc_insertion_point(field_set:Message.OTPid)
}

// optional bytes CT = 14;
inline bool Message::_internal_has_ct() const {
  bool value = (_has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline bool Message::has_ct() const {
  return _internal_has_ct();
}
inline void Message::clear_ct() {
  ct_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000100u;
}
inline const std::string& Message::ct() const {
  // @@protoc_insertion_point(field_get:Message.CT)
  return _internal_ct();
}
inline void Message::set_ct(const std::string& value) {
  _internal_set_ct(value);
  // @@protoc_insertion_point(field_set:Message.CT)
}
inline std::string* Message::mutable_ct() {
  // @@protoc_insertion_point(field_mutable:Message.CT)
  return _internal_mutable_ct();
}
inline const std::string& Message::_internal_ct() const {
  return ct_.GetNoArena();
}
inline void Message::_internal_set_ct(const std::string& value) {
  _has_bits_[0] |= 0x00000100u;
  ct_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void Message::set_ct(std::string&& value) {
  _has_bits_[0] |= 0x00000100u;
  ct_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Message.CT)
}
inline void Message::set_ct(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000100u;
  ct_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Message.CT)
}
inline void Message::set_ct(const void* value, size_t size) {
  _has_bits_[0] |= 0x00000100u;
  ct_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Message.CT)
}
inline std::string* Message::_internal_mutable_ct() {
  _has_bits_[0] |= 0x00000100u;
  return ct_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Message::release_ct() {
  // @@protoc_insertion_point(field_release:Message.CT)
  if (!_internal_has_ct()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000100u;
  return ct_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Message::set_allocated_ct(std::string* ct) {
  if (ct != nullptr) {
    _has_bits_[0] |= 0x00000100u;
  } else {
    _has_bits_[0] &= ~0x00000100u;
  }
  ct_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ct);
  // @@protoc_insertion_point(field_set_allocated:Message.CT)
}

// optional int32 messNum = 15;
inline bool Message::_internal_has_messnum() const {
  bool value = (_has_bits_[0] & 0x00010000u) != 0;
  return value;
}
inline bool Message::has_messnum() const {
  return _internal_has_messnum();
}
inline void Message::clear_messnum() {
  messnum_ = 0;
  _has_bits_[0] &= ~0x00010000u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Message::_internal_messnum() const {
  return messnum_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Message::messnum() const {
  // @@protoc_insertion_point(field_get:Message.messNum)
  return _internal_messnum();
}
inline void Message::_internal_set_messnum(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00010000u;
  messnum_ = value;
}
inline void Message::set_messnum(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_messnum(value);
  // @@protoc_insertion_point(field_set:Message.messNum)
}

// optional int32 prevNum = 16;
inline bool Message::_internal_has_prevnum() const {
  bool value = (_has_bits_[0] & 0x00020000u) != 0;
  return value;
}
inline bool Message::has_prevnum() const {
  return _internal_has_prevnum();
}
inline void Message::clear_prevnum() {
  prevnum_ = 0;
  _has_bits_[0] &= ~0x00020000u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Message::_internal_prevnum() const {
  return prevnum_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Message::prevnum() const {
  // @@protoc_insertion_point(field_get:Message.prevNum)
  return _internal_prevnum();
}
inline void Message::_internal_set_prevnum(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00020000u;
  prevnum_ = value;
}
inline void Message::set_prevnum(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_prevnum(value);
  // @@protoc_insertion_point(field_set:Message.prevNum)
}

// optional bytes senRKey = 17;
inline bool Message::_internal_has_senrkey() const {
  bool value = (_has_bits_[0] & 0x00000200u) != 0;
  return value;
}
inline bool Message::has_senrkey() const {
  return _internal_has_senrkey();
}
inline void Message::clear_senrkey() {
  senrkey_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000200u;
}
inline const std::string& Message::senrkey() const {
  // @@protoc_insertion_point(field_get:Message.senRKey)
  return _internal_senrkey();
}
inline void Message::set_senrkey(const std::string& value) {
  _internal_set_senrkey(value);
  // @@protoc_insertion_point(field_set:Message.senRKey)
}
inline std::string* Message::mutable_senrkey() {
  // @@protoc_insertion_point(field_mutable:Message.senRKey)
  return _internal_mutable_senrkey();
}
inline const std::string& Message::_internal_senrkey() const {
  return senrkey_.GetNoArena();
}
inline void Message::_internal_set_senrkey(const std::string& value) {
  _has_bits_[0] |= 0x00000200u;
  senrkey_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void Message::set_senrkey(std::string&& value) {
  _has_bits_[0] |= 0x00000200u;
  senrkey_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Message.senRKey)
}
inline void Message::set_senrkey(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000200u;
  senrkey_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Message.senRKey)
}
inline void Message::set_senrkey(const void* value, size_t size) {
  _has_bits_[0] |= 0x00000200u;
  senrkey_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Message.senRKey)
}
inline std::string* Message::_internal_mutable_senrkey() {
  _has_bits_[0] |= 0x00000200u;
  return senrkey_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Message::release_senrkey() {
  // @@protoc_insertion_point(field_release:Message.senRKey)
  if (!_internal_has_senrkey()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000200u;
  return senrkey_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Message::set_allocated_senrkey(std::string* senrkey) {
  if (senrkey != nullptr) {
    _has_bits_[0] |= 0x00000200u;
  } else {
    _has_bits_[0] &= ~0x00000200u;
  }
  senrkey_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), senrkey);
  // @@protoc_insertion_point(field_set_allocated:Message.senRKey)
}

// optional int32 recId = 18;
inline bool Message::_internal_has_recid() const {
  bool value = (_has_bits_[0] & 0x00040000u) != 0;
  return value;
}
inline bool Message::has_recid() const {
  return _internal_has_recid();
}
inline void Message::clear_recid() {
  recid_ = 0;
  _has_bits_[0] &= ~0x00040000u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Message::_internal_recid() const {
  return recid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Message::recid() const {
  // @@protoc_insertion_point(field_get:Message.recId)
  return _internal_recid();
}
inline void Message::_internal_set_recid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00040000u;
  recid_ = value;
}
inline void Message::set_recid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_recid(value);
  // @@protoc_insertion_point(field_set:Message.recId)
}

// optional string textContent = 19;
inline bool Message::_internal_has_textcontent() const {
  bool value = (_has_bits_[0] & 0x00000400u) != 0;
  return value;
}
inline bool Message::has_textcontent() const {
  return _internal_has_textcontent();
}
inline void Message::clear_textcontent() {
  textcontent_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000400u;
}
inline const std::string& Message::textcontent() const {
  // @@protoc_insertion_point(field_get:Message.textContent)
  return _internal_textcontent();
}
inline void Message::set_textcontent(const std::string& value) {
  _internal_set_textcontent(value);
  // @@protoc_insertion_point(field_set:Message.textContent)
}
inline std::string* Message::mutable_textcontent() {
  // @@protoc_insertion_point(field_mutable:Message.textContent)
  return _internal_mutable_textcontent();
}
inline const std::string& Message::_internal_textcontent() const {
  return textcontent_.GetNoArena();
}
inline void Message::_internal_set_textcontent(const std::string& value) {
  _has_bits_[0] |= 0x00000400u;
  textcontent_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void Message::set_textcontent(std::string&& value) {
  _has_bits_[0] |= 0x00000400u;
  textcontent_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Message.textContent)
}
inline void Message::set_textcontent(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000400u;
  textcontent_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Message.textContent)
}
inline void Message::set_textcontent(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000400u;
  textcontent_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Message.textContent)
}
inline std::string* Message::_internal_mutable_textcontent() {
  _has_bits_[0] |= 0x00000400u;
  return textcontent_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Message::release_textcontent() {
  // @@protoc_insertion_point(field_release:Message.textContent)
  if (!_internal_has_textcontent()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000400u;
  return textcontent_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Message::set_allocated_textcontent(std::string* textcontent) {
  if (textcontent != nullptr) {
    _has_bits_[0] |= 0x00000400u;
  } else {
    _has_bits_[0] &= ~0x00000400u;
  }
  textcontent_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), textcontent);
  // @@protoc_insertion_point(field_set_allocated:Message.textContent)
}

// optional string timestamp = 20;
inline bool Message::_internal_has_timestamp() const {
  bool value = (_has_bits_[0] & 0x00000800u) != 0;
  return value;
}
inline bool Message::has_timestamp() const {
  return _internal_has_timestamp();
}
inline void Message::clear_timestamp() {
  timestamp_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000800u;
}
inline const std::string& Message::timestamp() const {
  // @@protoc_insertion_point(field_get:Message.timestamp)
  return _internal_timestamp();
}
inline void Message::set_timestamp(const std::string& value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:Message.timestamp)
}
inline std::string* Message::mutable_timestamp() {
  // @@protoc_insertion_point(field_mutable:Message.timestamp)
  return _internal_mutable_timestamp();
}
inline const std::string& Message::_internal_timestamp() const {
  return timestamp_.GetNoArena();
}
inline void Message::_internal_set_timestamp(const std::string& value) {
  _has_bits_[0] |= 0x00000800u;
  timestamp_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void Message::set_timestamp(std::string&& value) {
  _has_bits_[0] |= 0x00000800u;
  timestamp_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Message.timestamp)
}
inline void Message::set_timestamp(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000800u;
  timestamp_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Message.timestamp)
}
inline void Message::set_timestamp(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000800u;
  timestamp_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Message.timestamp)
}
inline std::string* Message::_internal_mutable_timestamp() {
  _has_bits_[0] |= 0x00000800u;
  return timestamp_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Message::release_timestamp() {
  // @@protoc_insertion_point(field_release:Message.timestamp)
  if (!_internal_has_timestamp()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000800u;
  return timestamp_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Message::set_allocated_timestamp(std::string* timestamp) {
  if (timestamp != nullptr) {
    _has_bits_[0] |= 0x00000800u;
  } else {
    _has_bits_[0] &= ~0x00000800u;
  }
  timestamp_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), timestamp);
  // @@protoc_insertion_point(field_set_allocated:Message.timestamp)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::Message_MsgType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Message_MsgType>() {
  return ::Message_MsgType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_message_2eproto
